default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: event_center_callendar_development

test:
  <<: *default
  database: event_center_callendar_test

production:
  <<: *default
  database: event_center_callendar_production
  username: event_center_callendar
